# Generated by Django 5.0.7 on 2025-08-20 07:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_id', models.UUIDField()),
            ],
            options={
                'db_table': 'Connections',
            },
        ),
        migrations.CreateModel(
            name='DatabaseConnections',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_column='hostname', max_length=500, null=True)),
                ('username', models.CharField(db_column='username', max_length=500, null=True)),
                ('password', models.CharField(db_column='password', max_length=500, null=True)),
                ('database', models.CharField(db_column='database', max_length=500, null=True)),
                ('database_path', models.CharField(db_column='database_path', max_length=1500, null=True)),
                ('service_name', models.CharField(db_column='service_name', max_length=500, null=True)),
                ('port', models.IntegerField(db_column='port', null=True)),
                ('connection_name', models.CharField(db_column='connection_name', max_length=500, null=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('schema', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Database_Connections',
            },
        ),
        migrations.CreateModel(
            name='DataObjects',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=100)),
                ('object_name', models.CharField()),
            ],
            options={
                'db_table': 'DataObjects',
            },
        ),
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('type', models.CharField()),
            ],
            options={
                'db_table': 'DataSources',
            },
        ),
        migrations.CreateModel(
            name='FileConnections',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datapath', models.FileField(blank=True, db_column='file_path', max_length=1000, null=True, upload_to='Datamplify/files/')),
                ('source', models.CharField(blank=True, db_column='source_path', max_length=500, null=True)),
                ('connection_name', models.CharField(db_column='connection_name', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'File_connections',
            },
        ),
    ]
