# Generated by Django 5.0.7 on 2025-10-10 09:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconnections',
            name='dynamic_file_path',
            field=models.CharField(blank=True, db_column='dynamic_file_path', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_name_parameter',
            field=models.CharField(blank=True, db_column='file_name_parameter', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_host',
            field=models.CharField(blank=True, db_column='file_server_host', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_password',
            field=models.CharField(blank=True, db_column='file_server_password', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_port',
            field=models.CharField(blank=True, db_column='file_server_port', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_protocol',
            field=models.CharField(blank=True, db_column='file_server_protocol', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_type',
            field=models.CharField(blank=True, db_column='file_server_type', default='local', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_username',
            field=models.CharField(blank=True, db_column='file_server_username', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='use_dynamic_path',
            field=models.BooleanField(db_column='use_dynamic_path', default=False),
        ),
        migrations.CreateModel(
            name='CSVLoadConfiguration',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_name', models.CharField(db_column='config_name', max_length=200)),
                ('load_type', models.CharField(choices=[('DIRECT', 'Direct Load'), ('INDIRECT', 'Indirect Load')], db_column='load_type', max_length=20)),
                ('batch_size', models.IntegerField(db_column='batch_size', default=1000, null=True)),
                ('skip_rows', models.IntegerField(db_column='skip_rows', default=0, null=True)),
                ('delimiter', models.CharField(db_column='delimiter', default=',', max_length=10, null=True)),
                ('encoding', models.CharField(db_column='encoding', default='utf-8', max_length=50, null=True)),
                ('quote_char', models.CharField(db_column='quote_char', default='"', max_length=5, null=True)),
                ('escape_char', models.CharField(blank=True, db_column='escape_char', max_length=5, null=True)),
                ('staging_path', models.CharField(blank=True, db_column='staging_path', max_length=1000, null=True)),
                ('staging_table', models.CharField(blank=True, db_column='staging_table', max_length=200, null=True)),
                ('staging_schema', models.CharField(blank=True, db_column='staging_schema', max_length=200, null=True)),
                ('use_bulk_insert', models.BooleanField(db_column='use_bulk_insert', default=True)),
                ('truncate_before_load', models.BooleanField(db_column='truncate_before_load', default=False)),
                ('header_row', models.BooleanField(db_column='header_row', default=True)),
                ('null_values', models.JSONField(blank=True, db_column='null_values', default=list, null=True)),
                ('date_format', models.CharField(db_column='date_format', default='%Y-%m-%d', max_length=50, null=True)),
                ('timestamp_format', models.CharField(db_column='timestamp_format', default='%Y-%m-%d %H:%M:%S', max_length=50, null=True)),
                ('error_handling', models.CharField(choices=[('SKIP', 'Skip Errors'), ('ABORT', 'Abort on Error'), ('LOG', 'Log and Continue')], db_column='error_handling', default='SKIP', max_length=20)),
                ('max_errors', models.IntegerField(db_column='max_errors', default=100, null=True)),
                ('is_default', models.BooleanField(db_column='is_default', default=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CSV_Load_Configuration',
                'ordering': ['-is_default', 'config_name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalParameters',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(db_column='parameter_name', max_length=200, unique=True)),
                ('parameter_value', models.TextField(db_column='parameter_value')),
                ('parameter_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('PATH', 'File Path'), ('JSON', 'JSON Object')], db_column='parameter_type', max_length=50)),
                ('category', models.CharField(choices=[('DIRECT_LOAD', 'Direct Load'), ('INDIRECT_LOAD', 'Indirect Load'), ('GENERAL', 'General')], db_column='category', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Global_Parameters',
                'ordering': ['category', 'parameter_name'],
            },
        ),
    ]
