# Generated by Django 5.0.7 on 2025-10-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0003_fileconnections_dynamic_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_auth_file',
            field=models.FileField(blank=True, db_column='file_server_auth_file', max_length=1000, null=True, upload_to='Datamplify/auth_files/'),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='file_server_auth_type',
            field=models.CharField(blank=True, db_column='file_server_auth_type', default='password', max_length=20, null=True),
        ),
    ]
