# Generated by Django 5.2.4 on 2025-10-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks_Scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["-updated_at"]},
        ),
    ]
