# Generated by Django 5.0.7 on 2025-09-01 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scheduler', max_length=128)),
                ('owner', models.CharField(default='scheduler', max_length=64)),
                ('mode', models.CharField(choices=[('trigger', 'Trigger DAG'), ('bash', 'Bash/Command')], default='trigger', max_length=16)),
                ('schedule', models.CharField(blank=True, max_length=64, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('catchup', models.BooleanField(default=False)),
                ('max_active_runs', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('target_dag_id', models.CharField(blank=True, max_length=128, null=True)),
                ('bash_command', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
