# Generated by Django 5.0.7 on 2025-09-02 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBoard', '0004_remove_flowboard_catchup_remove_flowboard_is_active_and_more'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='flowboard',
            field=models.ForeignKey(blank=True, db_column='flowboard_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='FlowBoard.flowboard'),
        ),
    ]
