# Generated by Django 5.0.7 on 2025-09-01 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 5, 55, 38, 644936, tzinfo=datetime.timezone.utc)),
        ),
    ]
