# Generated by Django 5.0.7 on 2025-09-01 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 6, 22, 17, 361029, tzinfo=datetime.timezone.utc)),
        ),
    ]
