# Generated by Django 5.0.7 on 2025-10-07 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 9, 25, 2, 571251, tzinfo=datetime.timezone.utc)),
        ),
    ]
