# Generated by Django 5.0.7 on 2025-10-07 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 10, 6, 11, 809746, tzinfo=datetime.timezone.utc)),
        ),
    ]
