# Generated by Django 5.0.7 on 2025-10-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_account_activation_expiry_date'),
    ]

    operations = [
    ]
