# Generated by Django 5.0.7 on 2025-10-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_create_rbac_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 10, 11, 22, 563520, tzinfo=datetime.timezone.utc)),
        ),
    ]
