# Generated by Django 5.0.7 on 2025-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBoard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowboard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='flowboard',
            name='catchup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flowboard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flowboard',
            name='max_active_runs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flowboard',
            name='schedule',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='flowboard',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowboard',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        # Clean existing non-JSON DrawFlow values (e.g., plain URLs) before casting to JSON
        # Any value not starting with '{' or '[' will be reset to '{}'
        migrations.RunSQL(
            sql=''' 
                UPDATE "FlowBoard"
                SET "DrawFlow" =
                  CASE
                    WHEN "DrawFlow" IS NULL THEN '{}'
                    WHEN TRIM(CAST("DrawFlow" AS TEXT)) ~ '^[\\[{]' THEN "DrawFlow"
                    ELSE '{}'
                  END
            ''',
            reverse_sql=''' 
                -- no-op reverse for data cleanup
            ''',
        ),
        migrations.AlterField(
            model_name='flowboard',
            name='DrawFlow',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='flowboard',
            name='Flow_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flowboard',
            name='Flow_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flowboard',
            name='parsed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
