# Generated by Django 5.0.7 on 2025-09-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBoard', '0003_alter_flowboard_options_flowboard_catchup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowboard',
            name='catchup',
        ),
        migrations.RemoveField(
            model_name='flowboard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flowboard',
            name='max_active_runs',
        ),
        migrations.RemoveField(
            model_name='flowboard',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='flowboard',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='flowboard',
            name='timezone',
        ),
    ]
